### PR TITLE
Adding Docker Tags latest

### PR DESCRIPTION
**Pull request by peter279k**
As title, adding Docker tags to be latest and publish the Docker image with `latest` tag.

### CODE REVIEW

**Comment by peter279k** [comment]
Just notice that the Docker image publishing will be failed because the `docker login` step is failed.

And it should add repository secretes by repository owner to login current Docker Hub site.

**Comment by dmyers** [comment]
Fixed now. Thanks for that reminder. Rerunning last failed action now.

One thing I noticed was that it might not be super secure to pass in secrets through the `run` command, though they are masked in the logs, GitHub says it may not be entirely secret in some cases:
https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by peter279k** [comment]
Yes. You're right. But it's simpler than other approaches about secret encryption on GitHub Actions :).

**Comment by dmyers** [comment]
Yeah it's not a big deal at the moment I agree.

Have you started using PHP 8 yet? I'm thinking of adding that as the next build and marking `php74` as `latest` since 7.3 is no longer supported. https://www.php.net/supported-versions.php

**Comment by peter279k** [comment]
> Yeah it's not a big deal at the moment I agree.
> 
> Have you started using PHP 8 yet? I'm thinking of adding that as the next build and marking `php74` as `latest` since 7.3 is no longer supported. https://www.php.net/supported-versions.php

I plan to work on `php-8.0` now, but it seems that the Docker build with `php-8.0` version will be failed.

You can checkout my previous [building log about that](https://github.com/open-source-contributions/laravel-docker/runs/1611685379?check_suite_focus=true) :).

**Comment by peter279k** [comment]
The building error is about compiling `imagick`. The error message is as follows:

```
php_imagick_file.h:65:54: error: expected ';', ',' or ')' before 'TSRMLS_DC'
```

Some useful references are as follows:

- https://github.com/Imagick/imagick/issues/331
- https://bugs.php.net/bug.php?id=80474

**Comment by dmyers** [comment]
Hmm okay, we could just comment out that package install for now if it works without it until they support it.
